<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CapitalHumanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapitalHumanoRepository extends EntityRepository
{
}
