<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaDocenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaDocenteRepository extends EntityRepository
{
}