<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaCientificaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaCientificaRepository extends EntityRepository
{
}