<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EfemerideAmbientalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EfemerideAmbientalRepository extends EntityRepository
{
}