<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends EntityRepository
{
    public function findTop1()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT s FROM AppBundle:Empresa s ORDER BY s.id DESC'
        )->setMaxResults(1)->getResult();
    }
}