<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventoCSARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoCSARepository extends EntityRepository
{
    public function findTop4TiposServicio()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT s FROM AppBundle:EventoCSA s ORDER BY s.fechaInicial DESC'
        )->setMaxResults(4)->getResult();
    }
}
