<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventoCSARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoCSARepository extends EntityRepository
{
}
