<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoticiaAmbientalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaAmbientalRepository extends EntityRepository
{
}