<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoDeServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDeServicioRepository extends EntityRepository
{
    public function findTop6TiposServicio()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT s FROM AppBundle:TipoDeServicio s ORDER BY s.seMuestraEnPagInicial DESC'
        )->setMaxResults(6)->getResult();
    }
}
