<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoDeServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDeServicioRepository extends EntityRepository
{
}
